using System;
using Random = UnityEngine.Random;

namespace Common.Extensions
{
    //Generated by GPT because I'm lazy. It's a Fisher-Yates shuffle :p
    public static class ArrayExtensions
    {
        /// <summary>
        /// Shuffles the elements of the array in place using UnityEngine.Random.
        /// </summary>
        /// <typeparam name="T">The type of the array elements.</typeparam>
        /// <param name="array">The array to shuffle.</param>
        public static void Shuffle<T>(this T[] array)
        {
            if (array == null)
                throw new ArgumentNullException(nameof(array));

            int n = array.Length;
            for (int i = n - 1; i > 0; i--)
            {
                // UnityEngine.Random.Range is min inclusive and max exclusive.
                int j = Random.Range(0, i + 1);

                // Swap elements
                (array[i], array[j]) = (array[j], array[i]);
            }
        }
        
        /// <summary>
        /// Automatically keeps the index contained from [0, N] range where N is the size of the array.
        /// </summary>
        /// <param name="array"></param>
        /// <param name="value"></param>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public static int WrapIndex<T>(this T[] array, int value)
        {
            int length = array.Length;
            return ((value % length) + length) % length;
        }

        /// <summary>
        /// Returns true if the index is contained within the array.
        /// </summary>
        /// <param name="array"></param>
        /// <param name="index"></param>
        /// <typeparam name="T"></typeparam>
        /// <returns></returns>
        public static bool IsValidIndex<T>(this T[] array, int index) =>  index >= 0 && index < array.Length;
        
    }
}